"""Add last sync column

Revision ID: 41060afbd5db
Revises: b19f759c4c36
Create Date: 2020-10-30 16:09:53.730703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41060afbd5db'
down_revision = 'b19f759c4c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metasysCrawl', sa.Column('lastSync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


# This might not actually work.
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("This might fail due to DDL limitations in Sqlite.")
    op.drop_column('metasysCrawl', 'lastSync')
    # ### end Alembic commands ###
